import type { Metadata } from "next";
import { Roboto_Mono, Roboto_Slab } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Safe Journey Of Loppy",
  description: "Generated by create next app",
};

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto-slab",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${robotoMono.variable} ${robotoSlab.variable}`}>
      <body className="animate-fade-in">{children}</body>
    </html>
  );
}
